extraction:
  python:
    python_setup:
      version: 3

path_classifiers:
  test:
    - exclude: /
    - exclude: tests/util

queries:
  - include: '*'
  - exclude: 'py/uninitialized-local-variable'
